"""init tables

Revision ID: 9b6938b862f6
Revises: 
Create Date: 2026-02-05 09:31:09.749143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6938b862f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_cryptos_symbol')
    )
    op.create_index('ix_cryptos_name', 'cryptos', ['name'], unique=False)
    op.create_index('ix_cryptos_symbol', 'cryptos', ['symbol'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_strategies_code')
    )
    op.create_index('ix_strategies_code', 'strategies', ['code'], unique=False)
    op.create_index('ix_strategies_name', 'strategies', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'true'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', name='uq_users_telegram_id')
    )
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('take_profit_3', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('in_position', sa.Boolean(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptos.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index('ix_signals_crypto_id', 'signals', ['crypto_id'], unique=False)
    op.create_index('ix_signals_in_position_true', 'signals', ['in_position'], unique=False, postgresql_where=sa.text('in_position = true'))
    op.create_index('ix_signals_signal', 'signals', ['signal'], unique=False)
    op.create_index('ix_signals_strategy_id', 'signals', ['strategy_id'], unique=False)
    op.create_index('ix_signals_timeframe', 'signals', ['timeframe'], unique=False)
    op.create_index('ix_signals_user_id', 'signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_user_id', table_name='signals')
    op.drop_index('ix_signals_timeframe', table_name='signals')
    op.drop_index('ix_signals_strategy_id', table_name='signals')
    op.drop_index('ix_signals_signal', table_name='signals')
    op.drop_index('ix_signals_in_position_true', table_name='signals', postgresql_where=sa.text('in_position = true'))
    op.drop_index('ix_signals_crypto_id', table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_strategies_name', table_name='strategies')
    op.drop_index('ix_strategies_code', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_cryptos_symbol', table_name='cryptos')
    op.drop_index('ix_cryptos_name', table_name='cryptos')
    op.drop_table('cryptos')
    # ### end Alembic commands ###
